"""add time_spent to attempts

Revision ID: 09dd743afa8f
Revises: fb52d8159183
Create Date: 2026-01-30 16:00:54.540435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dd743afa8f'
down_revision: Union[str, Sequence[str], None] = 'fb52d8159183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('time_spent', sa.Integer(),server_default='0', nullable=False))
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('attempts', 'time_spent')
    # ### end Alembic commands ###
