"""add validation

Revision ID: 1861abeb8716
Revises: 2d3139233947
Create Date: 2026-02-08 14:35:30.044992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1861abeb8716'
down_revision: Union[str, Sequence[str], None] = '2d3139233947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_tasks', 'hint',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.create_index(op.f('ix_generated_tasks_difficulty'), 'generated_tasks', ['difficulty'], unique=False)
    op.create_index(op.f('ix_generated_tasks_subject'), 'generated_tasks', ['subject'], unique=False)
    op.create_index(op.f('ix_generated_tasks_title'), 'generated_tasks', ['title'], unique=False)
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_generated_tasks_title'), table_name='generated_tasks')
    op.drop_index(op.f('ix_generated_tasks_subject'), table_name='generated_tasks')
    op.drop_index(op.f('ix_generated_tasks_difficulty'), table_name='generated_tasks')
    op.alter_column('generated_tasks', 'hint',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
