"""add generated_tasks table

Revision ID: 2d3139233947
Revises: 5f6379702260
Create Date: 2026-02-08 14:21:02.093642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d3139233947'
down_revision: Union[str, Sequence[str], None] = '5f6379702260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('hint', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_table('generated_tasks')
    # ### end Alembic commands ###
