"""empty message

Revision ID: 3619da4c7ea2
Revises: 7f4a7d996b93
Create Date: 2026-02-03 20:31:45.530301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3619da4c7ea2'
down_revision: Union[str, Sequence[str], None] = '7f4a7d996b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_rank', sa.Enum('Бронза', 'Серебро', 'Золото', 'Элита', 'Сенсей', 'Легенда', name='rankname', native_enum=False), server_default='Бронза', nullable=False))
    op.alter_column('users', 'achievements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.VARCHAR(length=7), server_default=sa.text("'Бронза'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('users', 'achievements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.drop_column('users', 'user_rank')
    # ### end Alembic commands ###
