"""add is_active true TaskModel

Revision ID: 4f7df463642b
Revises: cdc53c750ad8
Create Date: 2026-02-09 11:49:33.233707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7df463642b'
down_revision: Union[str, Sequence[str], None] = 'cdc53c750ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_column('tasks', 'is_active')
    # ### end Alembic commands ###
