"""ALL achiev

Revision ID: 5f6379702260
Revises: 710ef35a87ef
Create Date: 2026-02-08 11:26:38.068883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6379702260'
down_revision: Union[str, Sequence[str], None] = '710ef35a87ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.add_column('users', sa.Column('all_achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('users', 'achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'all_achievements')
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
