"""drop winner_id

Revision ID: 710ef35a87ef
Revises: 82226ac76cef
Create Date: 2026-02-07 15:27:43.245046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710ef35a87ef'
down_revision: Union[str, Sequence[str], None] = '82226ac76cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pvp_matches', 'result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('pvp_matches_winner_id_fkey'), 'pvp_matches', type_='foreignkey')
    op.drop_column('pvp_matches', 'winner_id')
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.add_column('pvp_matches', sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pvp_matches_winner_id_fkey'), 'pvp_matches', 'users', ['winner_id'], ['id'])
    op.alter_column('pvp_matches', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
