"""add_users_and_elo

Revision ID: 7f4a7d996b93
Revises: 6bc661d9152a
Create Date: 2026-02-03 18:09:34.918129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4a7d996b93'
down_revision: Union[str, Sequence[str], None] = '6bc661d9152a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.Enum('Бронза', 'Серебро', 'Золото', 'Элита', 'Сенсей', 'Легенда', name='rankname', native_enum=False), server_default='Бронза', nullable=False))
    op.add_column('users', sa.Column('achievements', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'achievements')
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###
