"""add_attempt_stats_indices

Revision ID: ae036a4290fa
Revises: f61effccb59c
Create Date: 2026-02-05 14:54:21.906272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae036a4290fa'
down_revision: Union[str, Sequence[str], None] = 'f61effccb59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attempts_user_created', 'attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_attempts_user_task_correct_created', 'attempts', ['user_id', 'task_id', 'is_correct', 'created_at'], unique=False)
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_index('ix_attempts_user_task_correct_created', table_name='attempts')
    op.drop_index('ix_attempts_user_created', table_name='attempts')
    # ### end Alembic commands ###
