"""add cascade delete

Revision ID: b8f3e6c81071
Revises: 4f7df463642b
Create Date: 2026-02-11 17:11:35.693181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f3e6c81071'
down_revision: Union[str, Sequence[str], None] = '4f7df463642b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_constraint(op.f('attempts_user_id_fkey'), 'attempts', type_='foreignkey')
    op.create_foreign_key(None, 'attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_logs_admin_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('elo_history_user_id_fkey'), 'elo_history', type_='foreignkey')
    op.create_foreign_key(None, 'elo_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('generated_tasks_user_id_fkey'), 'generated_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'generated_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pvp_matches_player1_id_fkey'), 'pvp_matches', type_='foreignkey')
    op.drop_constraint(op.f('pvp_matches_player2_id_fkey'), 'pvp_matches', type_='foreignkey')
    op.create_foreign_key(None, 'pvp_matches', 'users', ['player2_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pvp_matches', 'users', ['player1_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'pvp_matches', type_='foreignkey')
    op.drop_constraint(None, 'pvp_matches', type_='foreignkey')
    op.create_foreign_key(op.f('pvp_matches_player2_id_fkey'), 'pvp_matches', 'users', ['player2_id'], ['id'])
    op.create_foreign_key(op.f('pvp_matches_player1_id_fkey'), 'pvp_matches', 'users', ['player1_id'], ['id'])
    op.drop_constraint(None, 'generated_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('generated_tasks_user_id_fkey'), 'generated_tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'elo_history', type_='foreignkey')
    op.create_foreign_key(op.f('elo_history_user_id_fkey'), 'elo_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_admin_id_fkey'), 'audit_logs', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.create_foreign_key(op.f('attempts_user_id_fkey'), 'attempts', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###
