"""init id False

Revision ID: cdc53c750ad8
Revises: 1861abeb8716
Create Date: 2026-02-08 14:49:34.452836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc53c750ad8'
down_revision: Union[str, Sequence[str], None] = '1861abeb8716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
