"""add tags and hint to tasks

Revision ID: d63b286c8d77
Revises: 683b35815440
Create Date: 2026-01-08 23:00:12.284224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63b286c8d77'
down_revision: Union[str, Sequence[str], None] = '683b35815440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('tasks', sa.Column('hint', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_tasks_theme'), table_name='tasks')
    op.drop_column('tasks', 'theme')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.add_column('tasks', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tasks_theme'), 'tasks', ['theme'], unique=False)
    op.drop_column('tasks', 'hint')
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###
