"""add Index and sql full text search

Revision ID: f61effccb59c
Revises: 3619da4c7ea2
Create Date: 2026-02-05 11:05:23.215671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f61effccb59c'
down_revision: Union[str, Sequence[str], None] = '3619da4c7ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index('ix_tasks_fts', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.create_index('ix_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('users', 'user_rank',
               existing_type=sa.VARCHAR(length=7),
               server_default='BRONZE',
               type_=sa.Enum('BRONZE', 'SILVER', 'GOLD', 'ELITE', 'SENSEI', 'LEGEND', name='rankname', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'achievements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'achievements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('users', 'user_rank',
               existing_type=sa.Enum('BRONZE', 'SILVER', 'GOLD', 'ELITE', 'SENSEI', 'LEGEND', name='rankname', native_enum=False),
               server_default=sa.text("'Бронза'::character varying"),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_index('ix_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.drop_index('ix_tasks_fts', table_name='tasks', postgresql_using='gin')
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
